### ISSUE TITLE
[Suggestion] Sort by level

### ISSUE THREAD

**Issue by gb410** [AndikaTanpaH/NecrobotJavanHawk#11]
It would be nice if the pokemon list could also be sorted by level.

Looking forward to the addition of favoriting/unfavoriting of Pokemons.

**Comment by AndikaTanpaH** [comment]
@gb410 please wait for new version, may tonight it will release for Sort by Level (i think this very usefull)
for un/favorite pokemon need custom the bot.

**Comment by AndikaTanpaH** [comment]
done latest release
