### ISSUE TITLE
No menus work for me

### ISSUE THREAD

**Issue by LaZzie** [AndikaTanpaH/NecrobotJavanHawk#13]
First, I am not blaming you or the code of the software. I respect what you've been doing for free, for us. On the latest version when I click an icon to open a menu I.E. (Pokeball to open the pokemon menu) nothing happens. What could that me? and if you need any information from me I will be glad you share it.

**Comment by AndikaTanpaH** [comment]
@LaZzie what bot? and the version? (Necrobot Forked/PokeMob)
Its stranger issue for me, never happened before
can you started bot from source? i need error/something information from your browser console.

**Comment by iwean** [comment]
Same for me here, menu not come when I click and profile window on the right down corner doesn't appear either... it's when I'm using TurningBot.... the older version JavanHawk 8.17 work fine with TurningBot.

But with NecroBot 9.3 run smooth.

**Comment by AndikaTanpaH** [comment]
I think TurningBot its another bot.. yeah I change something with new version to read what Bot used (for send different request to bot).
@iwean can you give me link TurningBot?

**Comment by iwean** [comment]
I use not from first release, but from discord version (edited version)

[TurningBot edited by Neil](http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/574325-turingbot-edited-neil-safe-fast-leveling.html)

I think necrobot get this killswitch from that bot...

**Comment by AndikaTanpaH** [comment]
@iwean bro try the latest version, i was try TurningBot and the bot not sending "TrainerProfile". Without that JavanHawk cannot read Exp, Level etc (I didnt found their source code)
View Pokemon (Evo/Transfer), Eggs, Items look fine.
Let me know if you got another error

**Comment by iwean** [comment]
@AndikaTanpaH Ok bro, you are doing great! I'm testing it right now.

Btw add color to IV % is very helpfull. Awesome !!!
