### ISSUE TITLE
[Suggestion] Menu for deleting poison & revive to give more space for pokeball. 

### ISSUE THREAD

**Issue by iwean** [AndikaTanpaH/NecrobotJavanHawk#14]
Can you give a menu for deleting poison & revive for make the bag only for pokeball & berry

When bot running it useles if we keep poison & revive.... 

Thx in advance my bro.... U r awesome!

**Comment by AndikaTanpaH** [comment]
@iwean I think it posible at now, i just check NecroBot ActionCommands/DropItemHandler.cs (update 1-2 days ago) there is the command action.. I'll check tomorow what we can do with this.
Maybe this didnt work for another bot.

**Comment by iwean** [comment]
Love your work!
