### ISSUE TITLE
i can't power up.

### ISSUE THREAD

**Issue by sevenkings001** [AndikaTanpaH/NecrobotJavanHawk#15]
I can't power up.

I can evolve,i can transfer.
But i cant power up.

I click the power up icon,there was no action.

I'm sure i have enough candy and stardust.

**Comment by AndikaTanpaH** [comment]
@sevenkings001 yup Power Up function need a custom the bot, because is not default command.

**Comment by khokhlovalexander** [comment]
What is a custom the bot needed? necrobot 0.9.6 Forked

**Comment by AndikaTanpaH** [comment]
@khokhlovalexander try https://github.com/AndikaTanpaH/NecrobotJavanHawk/releases/tag/v1.0.0 for this one.
