### ISSUE TITLE
[NOT RUN] Visualizer can not run with new realese Necrobot 0.9.6

### ISSUE THREAD

**Issue by iwean** [AndikaTanpaH/NecrobotJavanHawk#17]
Please check boss... I've done with websocket setting & port, but nothing happend.

**Comment by AndikaTanpaH** [comment]
bro @iwean its worked for me, maybe you miss google apikey or something. its no change at 0.9.6 websocket handler

**Comment by PreciousMetal** [comment]
On my screen with ver 0.9.6
Connecting to the bot (and never connect)

I use win 64

**Comment by PreciousMetal** [comment]
It's work, i forgot to change the socket set up : (become true)
