### ISSUE TITLE
Power Up issue

### ISSUE THREAD

**Issue by JakeCube** [AndikaTanpaH/NecrobotJavanHawk#20]
Currently i'm using Noxx/Necrobot 0.9.7 with JavanHawk,
the manually power up in GUI is not working... any solution?

**Comment by AndikaTanpaH** [comment]
@JakeCube because power up not on there yet..
for now you can only powerup with my build 'Necrobot0.9.6'  download from https://github.com/AndikaTanpaH/NecrobotJavanHawk/releases/tag/v1.0.0

I guess some issue on 0.9.7, little bug with msnipe.
