### ISSUE TITLE
PokeMobBot gets Error Messages

### ISSUE THREAD

**Issue by Sugarfloodwave** [AndikaTanpaH/NecrobotJavanHawk#6]
Hi!

The old visualizer worked with necro and MobBot! Yours does too but not very well because if you try to power up pa Pokemon you get an Error Message in the PokeMobbot. Maybe you can fix that?

EG: [21:03:55](ERROR) Unexpected character encountered while parsing value: P. Path '', line 0, position 0.
{"Command":"GetPokemonSettings"}

**Comment by AndikaTanpaH** [comment]
@Sugarfloodwave can you give me link for MobBot repo?
i'll check later.. and my custom didnt triger GetPokemonSettings, its just triger on the start

**Comment by Sugarfloodwave** [comment]
https://github.com/PocketMobsters/MobBotTemp

**Comment by vfuyong** [comment]
I can confirm this bug. It is great if your visualizer works for both of them :)

**Comment by AndikaTanpaH** [comment]
I just checked PokeMobBot, their websocket code look different..

I solved {"Command":"GetPokemonSettings"}, but i got more error, like:

> PokemonList
> [22:35:36](ERROR) Unexpected character encountered while parsing value: P. Path '', line 0, position 0.
> InventoryList
> [22:51:48](ERROR) Error parsing Infinity value. Path '', line 1, position 2.
> EggsList
> [22:51:53](ERROR) Unexpected character encountered while parsing value: E. Path '', line 0, position 0.

I dont seem "TrainerProfile", its for updating experience info etc, just a "playerStat" with minimal information.

I just try too with old visualizer, i got some error on cmd PokeMobBot.
I have written issue on [PocketMobsters](https://github.com/PocketMobsters/MobBotTemp/issues/138)

**Update** this morning MobBotTemp was gone :disappointed:

**Comment by Sugarfloodwave** [comment]
DMCA shut them down but they are all alive and well here: https://forum.pokemobbot.com with a new version and all if you are still into the project :)

Oh and if you didnt catch their response it was something a long the lines that your and the old visualiser are not using the correct json commands to get infos and thats why mobbot gives the errors. The correct Commands can be found in the WebsocketAPI.cs or something (doing this out of my head) but ask in the forum they are quite nice guys.

**Comment by AndikaTanpaH** [comment]
@Sugarfloodwave @vfuyong try new JavanHawk, its now support PokeMobBot
