### ISSUE TITLE
[Request] Manual Force Location to Walk to

### ISSUE THREAD

**Issue by Sugarfloodwave** [AndikaTanpaH/NecrobotJavanHawk#7]
That would be awesome if we can click on the map and the bot goes there. It is done here https://github.com/Lunat1q/Catchem-PoGo

maybe it can be implemented here as well

**Comment by AndikaTanpaH** [comment]
@Sugarfloodwave i'll check later.. I think need custom PokeMobBot to force walk/path cannot be done only from vizualizer

**Comment by AndikaTanpaH** [comment]
Merger to https://github.com/AndikaTanpaH/NecrobotJavanHawk/issues/18
