### ISSUE TITLE
[Suggestion] Skiplagged / pokemongomap map usage

### ISSUE THREAD

**Issue by Ezoteric** [AndikaTanpaH/NecrobotJavanHawk#8]
I think it would be perfect if you could use those maps as background.
Best way to catch good pokemon and level up is new york in my experience, and skiplagged has a nice and updated map :) 

Or let it use pokemongomap desktop so you can scan the area your in :)

Is this possible ? :)

**Comment by AndikaTanpaH** [comment]
Hi @Ezoteric im sorry for late respon, if you means a snipe its already at now.
I dont know how skiplagged doing with their api, if you have link with any document from their api i'll read it.

**Comment by AndikaTanpaH** [comment]
skiplagged, was implement for new release..
but its not for human walking snipe.. if you need more information just create new issue
