### ISSUE TITLE
[NOT RUN] Visualizer can not run with Necrobot 0.9.3

### ISSUE THREAD

**Issue by iwean** [AndikaTanpaH/NecrobotJavanHawk#9]
I change setting websocket on Necrobot 0.9.3 to "true", but nothing happen.

Ada solusi bro?

**Comment by AndikaTanpaH** [comment]
Whats the error message on JavanHawk?
make sure your config.json necrobot set true, and check the port

> "WebsocketsSettings": {
>     "UseWebsocket": true,
>     "WebSocketPort": 14251
>   },

JavanHawk default port is 14251, I just try with necrobot 0.9.3 and work fine.

**Comment by iwean** [comment]
Oh ok mas..... sip (y)

I changed it before, on the go... when the bot still run.
Now after I'm reload it... run like a charm!

Keren bro! Tararengkyu (y)
